# AUTOGENERATED! DO NOT EDIT! File to edit: ../blog/posts/nbdev_vs_quarto/nbdev_vs_quarto.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ../blog/posts/nbdev_vs_quarto/nbdev_vs_quarto.ipynb 3
def hello():
    print("Hello, world")
