# AUTOGENERATED! DO NOT EDIT! File to edit: ../study-demo/cryptography/plot.ipynb.

# %% auto 0
__all__ = ['bars', 'lines']

# %% ../study-demo/cryptography/plot.ipynb 0
import matplotlib.pyplot as plt
import numpy as np

# %% ../study-demo/cryptography/plot.ipynb 2
def bars(y):
    x = range(len(y))
    plt.bar(x, y)
    plt.show()

# %% ../study-demo/cryptography/plot.ipynb 4
def lines(x=None, y=None, y0=None, eq=False):
    plt.plot(x, y)
    if eq:
        plt.axis('equal')
    if y0 is not None:
        plt.ylim(bottom=y0)
    plt.show()
