project:
  type: website

website:
  title: "Sam's AI Blog"
  site-url: https://sam.ucm.dev/blog
  description: "recording my AI studies"
  navbar:
    right:
      - about.qmd
      - icon: house
        href: https://sam.ucm.dev/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
comments:
  hypothesis: true
