#!/bin/bash
interval=2
opts=
# opts="-d --log chatgpt.log"
while true; do
	v find . -name '*.chat' -newermt "-$interval seconds" | (
		count=0
		while read file; do
			echo "$file"
			<"$file" chatgpt $opts | tee -a "$file" &
			count=$[count+1]
		done
 		wait
		if [ $count -gt 0 ]; then
			v sleep $[$interval + 1]
		else
			v sleep $[$interval - 1]
		fi
	)
done
