#!/usr/bin/env python3

# split lines into sentences

import spacy
import sys

import argparse

def split_into_sentences(text):
	""" Split a text into sentences using spaCy's sentence segmentation. """
	doc = nlp(text)
	for sent in doc.sents:
		yield sent.text

def collect_paragraphs(stream):
	""" Collects lines into paragraphs. """
	paragraph = []
	for line in stream:
		line = line.rstrip()
		if line:
			paragraph.append(line)
		elif not line:
			yield " ".join(paragraph)
			paragraph = []
	if paragraph:
		yield " ".join(paragraph)

def main():
	parser = argparse.ArgumentParser(description='Split sentences')
	parser.add_argument('-m', '--model', default='en_core_web_sm', help='Model to use')

	args = parser.parse_args()

	nlp = spacy.load(args.model)

	inp = sys.stdin

	pgs = collect_paragraphs(inp)
	split_into_sentences(pgs)

	print("\n\n".join(map(lambda pg: "\n".join(map(str, split_into_sentences(pg))), pgs))

if __name__ == "__main__":
	main()
